# Generated by Django 4.2.7 on 2023-11-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('viewers', 'viewers')], default='admin', max_length=255, null=True),
        ),
    ]
